def parse(texts):
    # step 1: group each "node" to its subs "tok xxx, sub xx, subs xxx"
    grouped_texts = []
    group = []
    ast_list = []
    for text in texts:
        text = text.strip()
        if text == '' or text.startswith("#"): continue
        if text.startswith("node "):
            if group != []: grouped_texts.append(group)
            group = []
            text = text[5:]
            ast_list.append(text)
        group.append(text.strip())
    grouped_texts.append(group) # add the last remaining group
    # step 2: generate enum NodeType & baseNode
    source = []
    source.append("// This file is auto-generated by scipts/ast_gen.py.")
    source.append("// DO NOT EDIT THIS FILE. All your patches will be removed when recompiling.")
    source.append("")
    source.append("#pragma once")
    source.append("")
    source.append("#include \"infra.h\"")
    source.append("")
    source.append("enum NodeType {")
    for name in ast_list:
        source.append(f"    NODE_{name.upper()},")
    source.append("};")
    source.append("")
    for name in ast_list:
        source.append(f"class {name}Node;")
    source.append('')
    source.append("class Visitor;")
    source.append('')
    source.append("class BaseNode {")
    source.append("public:")
    source.append("    virtual ~BaseNode() {}")
    source.append("    virtual NodeType getType() = 0;")
    source.append("    virtual void *accept(const Visitor &vis) = 0;")
    source.append("    virtual void output() = 0;")
    source.append("};")
    source.append('')
    source.append("class Visitor {")
    source.append("public:")
    for name in ast_list:
        source.append(f"    virtual void *visit{name}Node({name}Node *node) const = 0;")
    source.append("")
    source.append("    void *visit(BaseNode *node) const {")
    source.append("        return node->accept(*this);")
    source.append("    }")
    source.append("};")
    source.append('')
    # step 4: for each group, generate its own AST structure
    for group in grouped_texts:
        source.append(f"class {group[0]}Node : public BaseNode " + "{")
        source.append("public:")
        # get subs & toks
        if len(group) == 1:
            # blank node
            source.append("    virtual void output() {")
            source.append(f"        io.print(\"{group[0]}Node[]\");")
            source.append("    }")
            source.append("")
        else:
            subs = []
            toks = []
            subss = []
            tokss = []
            requirements_without_prefix = []
            for requirements in group[1:]:
                if requirements.startswith("sub "):
                    subs.append(requirements[4:])
                    requirements_without_prefix.append(requirements[4:])
                elif requirements.startswith("tok "):
                    toks.append(requirements[4:])
                    requirements_without_prefix.append(requirements[4:])
                elif requirements.startswith("subs "):
                    subss.append(requirements[5:])
                    requirements_without_prefix.append(requirements[5:])
                elif requirements.startswith("toks "):
                    tokss.append(requirements[5:])
                    requirements_without_prefix.append(requirements[5:])
                else:
                    print(f"Error: unrecognizable prefix \"{requirements.split(' ')[0]}\" in AST definition of {group[0]}Node (expected 'tok', 'sub' or 'subs')")
                    exit()
            if toks: source.append("    Token " + ", ".join(toks) + ";")
            if subs: source.append("    BaseNode " + ", ".join(map(lambda name: "*" + name, subs)) + ";")
            if subss: source.append("    DynamicArray<BaseNode *> " + ", ".join(subss) + ";")
            if tokss: source.append("    DynamicArray<Token> " + ", ".join(tokss) + ";")
            # generate constructor
            constructor = f"    {group[0]}Node("
            for requirement in requirements_without_prefix:
                if requirement in subs:
                    constructor += f"BaseNode *{requirement}, "
                elif requirement in toks:
                    constructor += f"Token {requirement}, "
                elif requirement in subss:
                    constructor += f"const DynamicArray<BaseNode *> &{requirement}, "
                elif requirement in tokss:
                    constructor += f"const DynamicArray<Token> &{requirement}, "
            constructor = constructor[:-2] + ")"
            source.append(constructor)
            # generate idk what is that
            assigner = "      : "
            assigner += ", ".join(map(lambda x: f"{x}({x})", requirements_without_prefix))
            assigner += " {}"
            source.append(assigner)
            # generate deconstructor
            source.append(f"    virtual ~{group[0]}Node() " + "{")
            # delete sub & subs
            if subs: source.append("        " + "; ".join(map(lambda x: f"delete {x}", subs)) + ";")
            if subss: source.append("\n".join(map(lambda x: f"        for (int i = 0; i < {x}.size(); i++) delete {x}[i];", subss)))
            source.append("    }")
            # generate tostring
            # basic idea: tok -> .value, sub -> .tostring(), subs -> a concat for loop
            source.append("    virtual void output() {")
            source.append(f"        io.print(\"{group[0]}Node[\");")
            for index, requirement in enumerate(requirements_without_prefix):
                if requirement in toks:
                    source.append(f"        io.print(\"{', ' if index else ''}{requirement} = \", {requirement});")
                elif requirement in subs:
                    source.append(f"        io.print(\"{', ' if index else ''}{requirement} = \");")
                    source.append(f"        {requirement}->output();")
                elif requirement in tokss:
                    source.append(f"        io.print(\"{', ' if index else ''}{requirement} = [\");")
                    source.append(f"        for (int i = 0; i < {requirement}.size(); i++) ""{")
                    source.append(f"            {requirement}[i].output();")
                    source.append(f'            if (i != {requirement}.size() - 1) io.print(", ");')
                    source.append("        }")
                    source.append("        putchar(']');")
                elif requirement in subss:
                    source.append(f"        io.print(\"{', ' if index else ''}{requirement} = [\");")
                    source.append(f"        for (int i = 0; i < {requirement}.size(); i++) ""{")
                    source.append(f"            {requirement}[i]->output();")
                    source.append(f'            if (i != {requirement}.size() - 1) io.print(", ");')
                    source.append("        }")
                    source.append("        putchar(']');")
            source.append("        io.print(\"]\");")
            source.append("    }")
        
        source.append("    virtual NodeType getType() {")
        source.append(f"        return NODE_{group[0].upper()};")
        source.append("    }")
        source.append("    virtual void *accept(const Visitor &vis) {")
        source.append(f"        return vis.visit{group[0]}Node(this);")
        source.append("    }")
        source.append("};")
        source.append("")

    print("\n".join(source), end='')

def main(argv):
    with open(argv[1], "r") as f:
        texts = f.readlines()
    
    parse(texts)

if __name__ == '__main__':
    import sys
    main(sys.argv)